#!/usr/bin/env python3
import rclpy
from rclpy.node import Node
from geometry_msgs.msg import Vector3
from std_msgs.msg import String
import numpy as np
import csv
import os
from scipy.interpolate import CubicSpline

class CalibrationNode(Node):
    def __init__(self):
        super().__init__('calibration_node')

        # ===== RESOLVE WORKSPACE ROOT =====
        self.ws_root = os.path.expanduser('~/helmholtz_minimal_ws')
        
        # Internal Data Setup (Independent for X, Y, Z)
        self.splines = {'x': None, 'y': None, 'z': None}
        self.max_b = {'x': 0.0, 'y': 0.0, 'z': 0.0}

        default_csv_path = os.path.join(
            self.ws_root,
            'calibration_files',
            'calibration.csv' # Make sure this matches your dummy/real filename
        )

        # Load default calibration on startup
        self.load_csv(default_csv_path)

        # ===== ROS INTERFACES =====
        # Listens to the Commanded Field from the PID node
        self.sub_cmd = self.create_subscription(Vector3, 'b_cmd_internal', self.cmd_callback, 10)
        
        # Listens for GUI Calibration Updates from Auto-Sweep
        self.sub_ctrl = self.create_subscription(String, 'control_cmd', self.ctrl_cb, 10)
        
        # Publishes the final hardware signal to the Bridge
        self.pub = self.create_publisher(Vector3, 'pwm_cmd', 10)
        
        self.get_logger().info("Calibration Node (Feedforward) Ready.")

    def load_csv(self, csv_path):
        self.get_logger().info(f"Loading 4-Column Spline calibration: {csv_path}")

        pwm_raw, bx_raw, by_raw, bz_raw = [], [], [], []

        # ===== LOAD CSV =====
        try:
            with open(csv_path, 'r') as f:
                reader = csv.reader(f)
                for row in reader:
                    try:
                        # CSV Format: [PWM, Bx, By, Bz]
                        pwm_raw.append(abs(float(row[0])))
                        bx_raw.append(abs(float(row[1])))
                        by_raw.append(abs(float(row[2])))
                        bz_raw.append(abs(float(row[3])))
                    except (IndexError, ValueError):
                        continue

            if not pwm_raw:
                self.get_logger().error("CSV loaded but contains no valid data rows.")
                return

            # ===== AMBIENT BASELINE REMOVAL =====
            # The first row represents the Earth's ambient field in the lab
            amb_x, amb_y, amb_z = bx_raw[0], by_raw[0], bz_raw[0]
            
            # Clean the data by subtracting the ambient baseline
            bx_clean = [abs(b - amb_x) for b in bx_raw]
            by_clean = [abs(b - amb_y) for b in by_raw]
            bz_clean = [abs(b - amb_z) for b in bz_raw]

            # Convert to numpy arrays
            pwm_arr = np.array(pwm_raw)
            bx_arr = np.array(bx_clean)
            by_arr = np.array(by_clean)
            bz_arr = np.array(bz_clean)

            # ===== SORT, REMOVE DUPLICATES, AND BUILD SPLINES =====
            # np.unique automatically sorts lowest-to-highest and drops duplicate sensor readings
            # This prevents the CubicSpline "x must be strictly increasing" crash
            
            # X-Axis Spline
            bx_unique, idx_x = np.unique(bx_arr, return_index=True)
            self.splines['x'] = CubicSpline(bx_unique, pwm_arr[idx_x])
            self.max_b['x'] = bx_unique[-1]

            # Y-Axis Spline
            by_unique, idx_y = np.unique(by_arr, return_index=True)
            self.splines['y'] = CubicSpline(by_unique, pwm_arr[idx_y])
            self.max_b['y'] = by_unique[-1]

            # Z-Axis Spline
            bz_unique, idx_z = np.unique(bz_arr, return_index=True)
            self.splines['z'] = CubicSpline(bz_unique, pwm_arr[idx_z])
            self.max_b['z'] = bz_unique[-1]

            self.get_logger().info(f"3-Axis Splines successfully built. Baselines removed -> X:{amb_x:.1f} Y:{amb_y:.1f} Z:{amb_z:.1f}")
            
        except FileNotFoundError:
            self.get_logger().error(f"Calibration CSV not found at: {csv_path}")
        except Exception as e:
            self.get_logger().error(f"Failed to load calibration: {e}")

    def ctrl_cb(self, msg):
        """Listens for new calibration files generated by Auto-Sweep."""
        cmd = msg.data.strip()
        if cmd.startswith("CALIB:"):
            path = cmd.split(":", 1)[1]
            self.load_csv(path)

    def calculate_pwm(self, B_cmd, axis):
        """Translates Physics (µT) to Hardware (PWM)."""
        # Safety catch if splines failed to load or command is basically zero
        if self.splines[axis] is None or abs(B_cmd) < 1e-3:
            return 0.0
            
        sign = np.sign(B_cmd)
        abs_b = abs(B_cmd)
        
        # Clamp the requested field to the maximum tested field to prevent spline extrapolation errors
        abs_b = min(abs_b, self.max_b[axis])
        
        # Direct Spline translation
        pwm_raw = float(self.splines[axis](abs_b))
        
        # Clip to Arduino hardware limits
        pwm_final = np.clip(pwm_raw, 0.0, 255.0)
        
        return float(sign * pwm_final)

    def cmd_callback(self, msg):
        out = Vector3()
        # Process each axis through its dedicated feedforward spline
        out.x = self.calculate_pwm(msg.x, 'x')
        out.y = self.calculate_pwm(msg.y, 'y')
        out.z = self.calculate_pwm(msg.z, 'z')
        
        self.pub.publish(out)

def main(args=None):
    rclpy.init(args=args)
    node = CalibrationNode()
    try:
        rclpy.spin(node)
    except KeyboardInterrupt:
        pass
    finally:
        node.destroy_node()
        rclpy.shutdown()

if __name__ == '__main__':
    main()